#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bug report
description: File a bug report for the repository

body:
- type: markdown
  attributes:
    value: |
      **Your help in making AlpaSim better is greatly appreciated!**

      * Please ensure that:
        * The issue hasn't already been reported by using the [issue search](https://github.com/NVlabs/alpasim/issues).
      * For questions, please consider [open a discussion](https://github.com/NVlabs/alpasim/discussions).
      <br>

- type: textarea
  attributes:
    label: To Reproduce
    description: A clear and concise description of the bug/issue. Try to provide a minimal example to reproduce it.
    placeholder: |
      Markdown formatting might be applied to the text.

      ```python
      # use triple backticks for code blocks or terminal output/error messages
      ```

* Go to '...'
* Click on '....'
* Scroll down to '....'
* See error

  validations:
    required: true

- type: input
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen. 
    placeholder: Mp4 file should have been generated with loren ipsum.... 
  validations:
    required: true
- type: input
  attributes:
    label: Screenshots 
    placeholder: If applicable, add screenshots to help explain your problem. 
  validations:
    required: true

- type: input
  attributes:
    label: Desktop (please complete the following information): 
    placeholder: 

*OS:
*Nvidia driver/CUDA version (e.g. from nvidia-smi):
 
- type: textarea
  attributes:
    label: Additional information
    placeholder: Any other information that might be helpful.

